### ISSUE TITLE
feat: 사용자 매칭 추천 알고리즘 구현

### ISSUE THREAD

**Issue by Choi-Jiwon-38** [TEAM-LINRING/LINRING-BACK#5]
LINRING 사용자 매칭 시스템에 사용될 추천 알고리즘 구현과 적용된 시스템을 개발한다.

**도움말**
- `pip`를 이용하여 새로운 라이브러리, 패키지를 추가한 경우에는 requirements.txt에 해당 사항 반영해두기
> pip freeze > requirements.txt 명령어를 통하여 가능
- 추천 알고리즘의 선택의 경우에는 @Choi-Jiwon-38 , 혹은 지도 교수님께 confirm 받아두기

- [ ] 추천 알고리즘 구현
- [ ] 위 알고리즘이 적용된 매칭 시스템 구현

**Comment by rktlskan021** [comment]
프로토타입 LINRING에서 추천 알고리즘은 다음과 같음.
- 사용 데이터 : 유저의 위치 데이터, LINRING을 통해 만남을 성사시킨 횟수 데이터
- 알고리즘
 1. 국민대학교에서 반경 1km를 기준
    1-1. 현재 유저의 위치가 1km 안이면 위치 데이터를 이용해 가장 가까운 타유저부터 추천
    1-2. 현재 유저의 위치가 1km 밖이면 위치 데이터를 사용하지 않고, 만남을 성사시킨 횟수 데이터를 이용해 많이 이용해본 유저부터 추천
